### ISSUE TITLE
How to compile and use this?

### ISSUE THREAD

**Issue by phd21** [DamirPorobic/kImageAnnotator#19]
Hi Damir,

Hope all is well with you and yours.

How do we use this? How is it compiled for example in Ubuntu 16.04 which uses qt v5.6.1? Thank you.

Best regards,
Phil
phd21mint@gmail.com

**Comment by DamirPorobic** [comment]
Hey Phil, sorry for the late reply, I was on vacation and got back last night. 

The dependency is 5.6.2, but you could try to change following line in the top CMakeList.txt file 
`set(QT_MIN_VERSION "5.6.2")` to `set(QT_MIN_VERSION "5.6.1")`

If it works, good, otherwise, it's not going to work in its current state.

**Comment by DamirPorobic** [comment]
Seems to be working with 5.6.1, I've changed temporally the dependency to 5.6.1.

As always, you can build the same way you build ksnip, I'll update the readme.

**Comment by phd21** [comment]
Hi Damir,

Thank you. 

Changing that minor QT version should not be a problem for anyone.

I think I tried changing the CMakeList.txt to use 5.6.1, but it still did not compile or work for me in my Linux Mint KDE 18.3 based on Ubuntu 16.04 Xeniall, but I will certainly try again. May I ask what Linux system you are using? 

Best regards to you and yours,
Phil (phd21)

**Comment by DamirPorobic** [comment]
I'm using OpenSUSE 42.3 leap. 

What kind of error did you get? There was an issue in the cmake configuration that would break the build when you first time run `cmake ..` and show an error, something about being unable to find a resource file. When you tried to run `make` and then `cmake ..` again, it would work fine. I have fixed this issue today with commit 6225dc6673d125c119c875f8e583e3c4975b12f6

**Comment by phd21** [comment]
Hi Damir,

I hope you had a great vacation.

Ok, I downloaded the current source code and I was able to compile kimageannotator, yeah. Nice update to the readme, thank you. But, when I run it, all the tools create a rectangle and nothing shows on the "green" screen? Perhaps I do not know how to use it properly. I cannot select colors, size, etc... I would like a double arrow option as well, please...

Best regards,
Phil (phd21)

**Comment by DamirPorobic** [comment]
Strange, are you sure you're not using a the selection tool? When the color, size, etc. are grayed out, that indicates the selection tool. When you pick a tool that can draw something, the color and size picker should become available.
