### ISSUE TITLE
Add a double arrow option

### ISSUE THREAD

**Issue by phd21** [DamirPorobic/kImageAnnotator#23]
Hi Damir,

I hope this finds you and yours doing very well.

New features request
- add a double arrow option just like the current arrow option only with a double arrow. Should be able to duplicate the existing code with a different graphics (double arrow).

- allow multiple tool option changes without having to click tool option again. Example: If I click a tool's option to change the size, I have to re-click the tool option again to select a different color, etc...

Best regards,
Phil (phd21)
phd21mint@gmail.com

**Comment by DamirPorobic** [comment]
Implemented with 0.1.0
