### ISSUE TITLE
CAPS LOCK doesnt work on image editor

### ISSUE THREAD

**Issue by ussher** [DamirPorobic/kImageAnnotator#27]
Using 1.5.0-continuous build 450-a25e24b

In the image editor screen using the  T text tool hitting the CAPS LOCK key does not work to lock the text in ALL CAPS mode.  Holding down the shift+ entering the key does work to get the capitalized versions of the letters.

**Comment by DamirPorobic** [comment]
It looks like there is no Qt way to determine caps lock state. We need to implement something platform specific, maybe something like this in its own class:
```
bool checkCapsLock()
{
// platform dependent method of determining if CAPS LOCK is on
#ifdef Q_OS_WIN32 // MS Windows version
return GetKeyState(VK_CAPITAL) == 1;
#else // X11 version (Linux/Unix/Mac OS X/etc...)
Display * d = XOpenDisplay((char*)0);
bool caps_state = false;
if (d)
{
unsigned n;
XkbGetIndicatorState(d, XkbUseCoreKbd, &n);
caps_state = (n & 0x01) == 1;
}
return caps_state;
#endif
} 
```
