### ISSUE TITLE
Double-click on annotation area causes SIGSEGV crash

### ISSUE THREAD

**Issue by Snuggle** [DamirPorobic/kImageAnnotator#29]
Hey! If you grab the Number tool and click twice in **one location**, Ksnip crashes with a SIGSEGV.
Using the latest ksnip v1.5.0 continuous AppImage on Arch Linux.
`fish: “./ksnip-1.5.0-continuous-x86_64…” terminated by signal SIGSEGV (Address boundary error)`

This is a relatively minor bug, as no crash occurs if you _move_ the mouse while clicking. Example below:
![image](https://user-images.githubusercontent.com/26250962/49867452-78826000-fe02-11e8-9e42-eb8654be5129.png)

**Comment by DamirPorobic** [comment]
@sayed-anwar troubleshooting continues under this issue.

**Comment by DamirPorobic** [comment]
Should be fixed now
