### ISSUE TITLE
Some blurs get removed when losing focus

### ISSUE THREAD

**Issue by Cqoicebordel** [DamirPorobic/kImageAnnotator#35]
* Capture a window
* Blur several spot on the image
* Click outside of Ksnip window
=> Most of the blurs get removed when they shouldn't.

Ctrl+z'ing them and then ctrl+shift+z'ing bring them back.

**Comment by DamirPorobic** [comment]
Interesting, looks like all but the first are removed. Clicking again on them brings them back. 

Will look into it.

**Comment by DamirPorobic** [comment]
Should be fixed now
