### ISSUE TITLE
Add icons for dark theme

### ISSUE THREAD

**Issue by Cqoicebordel** [DamirPorobic/kImageAnnotator#37]
In a dark theme (breeze-dark here) the icons are barely visible. An image is worth a thousand words :
![image](https://user-images.githubusercontent.com/2286246/52339279-f468e500-2a0c-11e9-900e-e186020643fe.png)

**Comment by DamirPorobic** [comment]
I do had a plan to add light color icons, but had no time yet. Valid feature request.

**Comment by Cqoicebordel** [comment]
Note that :
* Ksnip is also affected (just in case you didn't notice)
* Since all icons are SVG and in a single color, it might be possible to change the color dynamically depending on the theme, either through modification of the SVG itself (by populating the colors dynamically), or through CSS.

**Comment by DamirPorobic** [comment]
Yes, I'm aware of it. I will probably create a light set of icons and add a loader which checks the theme color and loads the correct icon.

**Comment by Cqoicebordel** [comment]
That's what I meant : You don't need another set of icons, you just have to set the fill, and the fill stroke of the SVG, to the OS theme value.
For example, http://cqoicebordel.free.fr/SVGExample/. The color is changed via CSS and nothing else is done (it's twice the SVG present in your repo (a bit cleaned though)).
And you can do that using `myPushButton->setStyleSheet("* { fill: blue }");`
See http://doc.qt.io/qt-5/stylesheet-syntax.html

**Comment by Cqoicebordel** [comment]
(I'm not familiar with the C++ side of Qt, so I might be mistaken, but QStyle could do the same, I think)

**Comment by DamirPorobic** [comment]
Might be working, but I had bad experience with QStyleSheets in the past as they could behave differently on different systems, so usually use them as kind of last option. kImageAnnotator should not be the problem, all icons are svg, in ksnip however, some icons are png and I've tried recently to port them to svg but the small ones look blurry due to downscaling. Upscaling looks ok.

**Comment by DamirPorobic** [comment]
Added support in ksnip too
