### ISSUE TITLE
The undo function does not work on Crop tool commands.

### ISSUE THREAD

**Issue by antrrax** [DamirPorobic/kImageAnnotator#56]
I use Linux Mint 19.2 x64 Cinnamon
Git clone: August 11, 2019

1. Do any drawing
<a href="https://ibb.co/PMcw0s4"><img src="https://i.ibb.co/cw6DVKt/01.png" alt="01" border="0"></a>

2. Main Menu> Edit > Crop
<a href="https://ibb.co/m59Kp7f"><img src="https://i.ibb.co/tpq6R5V/02.png" alt="02" border="0"></a>

3. Move selection to crop image
<a href="https://ibb.co/4VTxXVX"><img src="https://i.ibb.co/3CNHjCj/03.png" alt="03" border="0"></a>

4. Mani Menu> Edit > Undo
<a href="https://ibb.co/y5drhB1"><img src="https://i.ibb.co/hHLSX1j/04.png" alt="04" border="0"></a>

It should undo step 3, but it undoes step 1
<a href="https://ibb.co/7XBFGpx"><img src="https://i.ibb.co/yXKJ8km/05.png" alt="05" border="0"></a>

The undo function does not work on Crop tool commands.

**Comment by DamirPorobic** [comment]
Thanks for opening this, looks indeed like a bug

**Comment by DamirPorobic** [comment]
It seems to be working on my machine. Could you test again with the AppImage?

![crop_with_undo](https://user-images.githubusercontent.com/12796236/64015514-fb7c4f80-cb24-11e9-939a-3bf14e32bb70.gif)

**Comment by DamirPorobic** [comment]
Oh wait, you're clicking on undo before you have actually cropped the image? That of course can't work, the crop is commited after you click on crop.

**Comment by DamirPorobic** [comment]
The only think that we might need to do here is disable undo&redo during crop operation.

**Comment by DamirPorobic** [comment]
Undo&redo is now disabled during crop and scale operation.
