### ISSUE TITLE
Text tool does not allow me to type accents

### ISSUE THREAD

**Issue by antrrax** [DamirPorobic/kImageAnnotator#57]
I use Linux Mint 19.2 x64 Cinnamon
Git clone: August 11, 2019

Text tool does not allow me to type accents or is not compatible with my keyboard standard.

**keyboard key:**
acute accent
back accent

**another key:**
circumflex accent
tilting accent

**another key:**
trembling accent

-------------
comand: $ locale
LANG=pt_BR.UTF-8
LANGUAGE=pt_BR
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY=pt_BR.UTF-8
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER=pt_BR.UTF-8
LC_NAME=pt_BR.UTF-8
LC_ADDRESS=pt_BR.UTF-8
LC_TELEPHONE=pt_BR.UTF-8
LC_MEASUREMENT=pt_BR.UTF-8
LC_IDENTIFICATION=pt_BR.UTF-8
LC_ALL=

**Comment by DamirPorobic** [comment]
Is this something language specific? Might be related to #59

**Comment by DamirPorobic** [comment]
Bug #59 should be fixed now so maybe this one too, could you please test?

**Comment by DamirPorobic** [comment]
I think I got your issue wrong, you were not able to input 
![image](https://user-images.githubusercontent.com/12796236/64122598-67b7b700-cda2-11e9-9cc5-7ed468ad7e50.png)

**Comment by DamirPorobic** [comment]
Should be also fixed now, if that was your issue.

**Comment by DamirPorobic** [comment]
Closing this issue, in case this is still not working for you, please reopen the issue.
