### ISSUE TITLE
Ctrl Modifier stuck on second or third screenshot with Ctrl-N

### ISSUE THREAD

**Issue by cdoubleplusgood** [DamirPorobic/kImageAnnotator#58]
System: Windows 10 Pro Version 1803 64 bit
Version: 1.5.0 Build: 683-1e81649

Steps to reproduce:
1. Start ksnip
2. Capture a screenshot with Ctrl-N
3. Draw a rectangle (R)
4. Capture another screenshot with Ctrl-N (Prompt to save before discarding... is off)
5. Draw a rectangle (R) in the new screenshot.

Observation: In the second screenshot only squares and circles are possible; arrows can only be drawn in 0, 45, 90, 135... degree angles.
Sometimes you must take a 3rd screenshot to trigger the bug.
This happens only when starting the screenshot with Ctrl-N. The bug does not occur when clicking the "New" button in the toolbar, or "New" in the menu.

![ksnip_20190607-232612](https://user-images.githubusercontent.com/51495766/59134497-adb7d700-897b-11e9-9a9e-3ca8bbc32813.png)

**Comment by DamirPorobic** [comment]
Should be fixed now. What happen is that `ctrl` is also the modifier key for like drawing straight lines or rectangles or circles so when you press `ctrl+N` to trigger a new screenshot we detected that `ctrl` was pressed but the the snipping area is opened and we don't get that `ctrl` is released now. I'm resetting the internal storage for pressed keys any time we get a new screenshot.
