### ISSUE TITLE
Increase blur level so that large text is not visible

### ISSUE THREAD

**Issue by Ridbowt** [DamirPorobic/kImageAnnotator#62]
Would you mind adding _a stronger_ **"Blur Level"?** Now the maximum level _is 20._ But this is clearly not enough to effectively **blur large text.**

<a href="https://imgur.com/s5WSOGy"><img src="https://i.imgur.com/s5WSOGy.png" title="source: imgur.com" /></a>

**Comment by DamirPorobic** [comment]
Thanks for opening this issue. I had a quick look, we probably need to adjust the algorithm that does that blurring.

**Comment by DamirPorobic** [comment]
I've increased the blur level, here the compression of a Text written with Font size 60 and a blur level of 20:
![image](https://user-images.githubusercontent.com/12796236/65623662-99e6be00-dfc8-11e9-8d8a-893add28cf52.png)

**Comment by DamirPorobic** [comment]
Closing issue. If the blur level is still not sufficient please reopen the issue.
