### ISSUE TITLE
On startup does not highlight the tool, when this tool is not the first item in the list.

### ISSUE THREAD

**Issue by antrrax** [DamirPorobic/kImageAnnotator#63]
I use Linux Mint 19.2 x64 Cinnamon
Git clone: September 14, 2019

**On startup - Does not highlight the tool, when this tool is not the first item in the list**

I make a capture and in Annotator I choose one of the tools that have more than one option, eg Marker; Arrow / Line or geometric shape.
In these specific tools when I choose the first option, eg Arrow (A), then close ksnip.
<a href="https://ibb.co/nrgJxK6"><img src="https://i.ibb.co/SNsCFZ5/tool02.png" alt="tool02" border="0"></a>

I open ksnip again, make a new capture. It highlights the "Arrow (A)" tool {this is the expected behavior}
<a href="https://ibb.co/D1qc58j"><img src="https://i.ibb.co/PrSXw9V/tool03.png" alt="tool03" border="0"></a>

----

But in tools with more than one option, I choose anything other than the first one, eg Double Arrow (D), then close ksnip.
<a href="https://ibb.co/KFLpD8y"><img src="https://i.ibb.co/QrC3kxm/tool04.png" alt="tool04" border="0"></a>

I open ksnip again, make a new capture. **It does not highlight any tools**, but it remembers that the last tool used was Double Arrow (D) and so I can draw in Annotator that the Double Arrow object will appear.
<a href="https://ibb.co/dmz3CY9"><img src="https://i.ibb.co/J3Mb6JL/tool05.png" alt="tool05" border="0"></a>

Expected Behavior:
When starting Annotator. The icon of the last tool used should be displayed in the sidebar, even when this tool is not the first option in the popup menu.

**Comment by DamirPorobic** [comment]
Good catch, will have a look at it.

**Comment by DamirPorobic** [comment]
Fixed
