### ISSUE TITLE
Multi-tool buttons select current (last) tool on single click

### ISSUE THREAD

**Issue by MurzNN** [DamirPorobic/kImageAnnotator#66]
Some toolbar buttons in editor interface have more than one action. Now we must always select needed tool from dropdown list after click. For example, if I want to draw rectangle, I must click on rectangle icon and, after this, select rectangle again from dropdown list.

Will be better to select current (last) instrument on simple single click, and provide list of instruments on long click or right-click.

**Comment by DamirPorobic** [comment]
Done for the last tool. Single click actives the default tool for that button. Holding down click activates a popup menu where you can selected a different default tool.
